export const CREATE_SPECIAL_REQUEST = "CREATE_SPECIAL_REQUEST";
export const CREATE_SPECIAL_SUCCESS = "CREATE_SPECIAL_SUCCESS";
export const CREATE_SPECIAL_FAIL = "CREATE_SPECIAL_FAIL";

export const GET_SPECIALITIES_REQUEST = "GET_SPECIALITIES_REQUEST";
export const GET_SPECIALITIES_SUCCESS = "GET_SPECIALITIES_SUCCESS";
export const GET_SPECIALITIES_FAIL = "GET_SPECIALITIES_FAIL";

export const GET_SPECIFIC_SPECIAL_REQUEST = "GET_SPECIFIC_SPECIAL_REQUEST";
export const GET_SPECIFIC_SPECIAL_SUCCESS = "GET_SPECIFIC_SPECIAL_SUCCESS";
export const GET_SPECIFIC_SPECIAL_FAIL = "GET_SPECIFIC_SPECIAL_FAIL";

export const DELETE_SPECIAL_REQUEST = "DELETE_SPECIAL_REQUEST";
export const DELETE_SPECIAL_SUCCESS = "DELETE_SPECIAL_SUCCESS";
export const DELETE_SPECIAL_FAIL = "DELETE_SPECIAL_FAIL";

export const UPDATE_SPECIAL_REQUEST = "UPDATE_SPECIAL_REQUEST";
export const UPDATE_SPECIAL_SUCCESS = "UPDATE_SPECIAL_SUCCESS";
export const UPDATE_SPECIAL_FAIL = "UPDATE_SPECIAL_FAIL";
