export const COUNTRIES_REQUEST = "COUNTRIES_REQUEST";
export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS";
export const COUNTRIES_FAIL = "COUNTRIES_FAIL";

export const CITIES_REQUEST = "CITIES_REQUEST";
export const CITIES_SUCCESS = "CITIES_SUCCESS";
export const CITIES_FAIL = "CITIES_FAIL";

export const ATTCH_IMG_REQUEST = "ATTCH_IMG_REQUEST";
export const ATTCH_IMG_SUCCESS = "ATTCH_IMG_SUCCESS";
export const ATTCH_IMG_FAIL = "ATTCH_IMG_FAIL";
